version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: adms
      POSTGRES_USER: adms_user
      POSTGRES_PASSWORD: adms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - adms_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://adms_user:adms_password@postgres:5432/adms
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend
    networks:
      - adms_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - adms_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  adms_network:
    driver: bridge
